### PR TITLE
feat: add the context parameter for middleware.Do

### PR DESCRIPTION
**Pull request by tq0fqeu**
add the context parameter for middleware.Do, fix some spell errors  and go fmt

### CODE REVIEW

**Comment by jiangz222** [comment]
Thanks a lot, What about using the `context` as the first parameter?

**Comment by tq0fqeu** [comment]
> Thanks a lot, What about using the `context` as the first parameter?

it's better, and the patch coverage seems could not hit the target because of some spelling error fixes

**Comment by tq0fqeu** [comment]
any suggestion? If not, plz merge the request and make a tag
I don't want to use the local private repo 😂

**Comment by jiangz222** [comment]
> any suggestion? If not, plz merge the request and make a tag
> I don't want to use the local private repo 😂

I will do it ASAP! 😃

**Review by jiangz222 — APPROVED** [review]
👍

**Pull request merged**
